name: GitHub Readme YouTube Cards
on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: DenverCoder1/github-readme-youtube-cards@main
        id: youtube-cards
        with:
          channel_id: UCxtclRELEt2-HdjjTQJJBXA
          comment_tag_name: YOUTUBE-CARDS
          show_duration: true
          youtube_api_key: ${{ secrets.YOUTUBE_API_KEY }}
